title:              George Cross IV - Blog
email:              GeorgeCross4@hotmail.com
description:        George's Technical Blog
author:             George Cross IV
baseurl:            ""
url:                "https://GeorgeCrossIV.github.io"

remote_theme: jekyll-theme-clean-blog

# Social Profiles
twitter_username:   DrGeorgeCrossIV
github_username:    GeorgeCrossIV
facebook_username:  
instagram_username:  
linkedin_username: dr-george-cross-iv

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
